from django.urls import path

from standalone import views

app_name = "standalone"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.StandaloneLogoutView.as_view(), name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("teacher/", views.teacher_dashboard, name="teacher_dashboard"),
    path("teacher/invite/", views.teacher_invite_create, name="teacher_invite"),
    path("teacher/activate/<uuid:token>/", views.teacher_activate, name="teacher_activate"),
    path("teacher/courses/new/", views.course_create, name="course_create"),
    path("teacher/courses/<int:course_id>/", views.course_detail, name="course_detail"),
    path("teacher/courses/<int:course_id>/delete/", views.course_delete, name="course_delete"),
    path("teacher/courses/<int:course_id>/student-preview/", views.student_preview, name="student_preview"),
    path(
        "teacher/courses/<int:course_id>/student-preview/blocks/<int:block_id>/<str:action>/",
        views.student_preview_action,
        name="student_preview_action",
    ),
    path("teacher/courses/<int:course_id>/update/<str:field_name>/", views.update_course_field, name="update_course_field"),
    path("teacher/courses/<int:course_id>/regenerate-content/", views.regenerate_course_content, name="regenerate_course_content"),
    path("teacher/courses/<int:course_id>/config/", views.course_config_edit, name="course_config"),
    path("teacher/courses/<int:course_id>/allowed-emails/new/", views.add_allowed_email, name="allowed_email_add"),
    path("teacher/courses/<int:course_id>/invite-student/", views.student_invite_create, name="student_invite"),
    path("teacher/courses/<int:course_id>/magic-link/", views.magic_link_create, name="magic_link_create"),
    path("teacher/courses/<int:course_id>/import-pdf/", views.course_import_upload, name="course_import_upload"),
    path("teacher/course-imports/<int:import_id>/", views.course_import_review, name="course_import_review"),
    path("teacher/courses/<int:course_id>/blocks/new/", views.block_create, name="block_create"),
    path("teacher/courses/<int:course_id>/generate-bank/", views.generate_course_bank, name="generate_course_bank"),
    path("teacher/courses/<int:course_id>/approve-questions/", views.approve_course_questions, name="approve_course_questions"),
    path("teacher/courses/<int:course_id>/validation-events/new/", views.validation_event_create, name="validation_event_create"),
    path("teacher/blocks/<int:block_id>/delete/", views.block_delete, name="block_delete"),
    path("teacher/blocks/<int:block_id>/regenerate-content/", views.regenerate_block_content, name="regenerate_block_content"),
    path("teacher/blocks/<int:block_id>/update/<str:field_name>/", views.update_block_field, name="update_block_field"),
    path("teacher/blocks/<int:block_id>/config/<str:field_name>/", views.update_block_config_field, name="update_block_config_field"),
    path("teacher/blocks/<int:block_id>/upload/", views.asset_upload, name="asset_upload"),
    path("teacher/assets/<int:asset_id>/delete/", views.delete_asset, name="delete_asset"),
    path("teacher/objectives/<int:objective_id>/move/<str:direction>/", views.move_learning_objective_view, name="move_learning_objective"),
    path("teacher/assets/<int:asset_id>/toggle/", views.toggle_asset_generation, name="toggle_asset_generation"),
    path("teacher/objectives/<int:objective_id>/update/", views.update_learning_objective, name="update_learning_objective"),
    path("teacher/objectives/<int:objective_id>/delete/", views.delete_learning_objective_view, name="delete_learning_objective"),
    path("teacher/validation-events/<int:event_id>/pack.pdf", views.validation_pack_pdf, name="validation_pack_pdf"),
    path("student/", views.student_dashboard, name="student_dashboard"),
    path("student/invite/<uuid:token>/", views.student_activate, name="student_activate"),
    path("courses/<slug:course_slug>/self-enrol/", views.self_enrol, name="self_enrol"),
    path("courses/magic/<uuid:token>/", views.magic_enrol, name="magic_enrol"),
    path("student/validation-events/<int:event_id>/book/", views.validation_book, name="validation_book"),
    path("student/bookings/<int:booking_id>/cancel/", views.validation_cancel, name="validation_cancel"),
    path(
        "student/courses/<int:course_id>/practice/blocks/<int:block_id>/<str:action>/",
        views.student_practice_action,
        name="student_practice_action",
    ),
    path("student/courses/<int:course_id>/practice/", views.practice_quiz, name="practice_quiz"),
]
