from django.urls import path

from standalone import views

app_name = "standalone"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.StandaloneLogoutView.as_view(), name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("teacher/", views.teacher_dashboard, name="teacher_dashboard"),
    path("teacher/invite/", views.teacher_invite_create, name="teacher_invite"),
    path("teacher/activate/<uuid:token>/", views.teacher_activate, name="teacher_activate"),
    path("teacher/courses/new/", views.course_create, name="course_create"),
    path("teacher/courses/<int:course_id>/", views.course_detail, name="course_detail"),
    path("teacher/courses/<int:course_id>/delete/", views.course_delete, name="course_delete"),
    path("teacher/courses/<int:course_id>/student-preview/", views.student_preview, name="student_preview"),
    path("teacher/courses/<int:course_id>/student-validate/", views.preview_student_validate, name="preview_student_validate"),
    path(
        "teacher/courses/<int:course_id>/student-validate/<str:action>/",
        views.preview_student_validate_action,
        name="preview_student_validate_action",
    ),
    path("teacher/courses/<int:course_id>/validation-practice/", views.preview_validation_practice, name="preview_validation_practice"),
    path(
        "teacher/courses/<int:course_id>/validation-practice/<str:action>/",
        views.preview_validation_practice_action,
        name="preview_validation_practice_action",
    ),
    path(
        "teacher/courses/<int:course_id>/student-preview/blocks/<int:block_id>/<str:action>/",
        views.student_preview_action,
        name="student_preview_action",
    ),
    path("teacher/courses/<int:course_id>/update/<str:field_name>/", views.update_course_field, name="update_course_field"),
    path(
        "teacher/courses/<int:course_id>/config/<str:field_name>/",
        views.update_course_config_field,
        name="update_course_config_field",
    ),
    path("teacher/courses/<int:course_id>/regenerate-content/", views.regenerate_course_content, name="regenerate_course_content"),
    path("teacher/courses/<int:course_id>/config/", views.course_config_edit, name="course_config"),
    path("teacher/courses/<int:course_id>/allowed-emails/new/", views.add_allowed_email, name="allowed_email_add"),
    path("teacher/courses/<int:course_id>/invite-student/", views.student_invite_create, name="student_invite"),
    path("teacher/courses/<int:course_id>/magic-link/", views.magic_link_create, name="magic_link_create"),
    path("teacher/courses/<int:course_id>/demo/regenerate/", views.demo_link_regenerate, name="demo_link_regenerate"),
    path("teacher/courses/<int:course_id>/import-pdf/", views.course_import_upload, name="course_import_upload"),
    path("teacher/course-imports/<int:import_id>/", views.course_import_review, name="course_import_review"),
    path("teacher/courses/<int:course_id>/blocks/new/", views.block_create, name="block_create"),
    path("teacher/courses/<int:course_id>/generate-bank/", views.generate_course_bank, name="generate_course_bank"),
    path("teacher/courses/<int:course_id>/approve-questions/", views.approve_course_questions, name="approve_course_questions"),
    path("teacher/courses/<int:course_id>/validation-events/new/", views.validation_event_create, name="validation_event_create"),
    path("teacher/validation-events/<int:event_id>/delete/", views.validation_event_delete, name="validation_event_delete"),
    path("teacher/validation-events/<int:event_id>/room-display/", views.validation_room_display, name="validation_room_display"),
    path("teacher/validation-events/<int:event_id>/room-display/data/", views.validation_room_display_data, name="validation_room_display_data"),
    path("teacher/validation-events/<int:event_id>/release-feedback/", views.validation_feedback_release, name="validation_feedback_release"),
    path("teacher/blocks/<int:block_id>/delete/", views.block_delete, name="block_delete"),
    path("teacher/blocks/<int:block_id>/move/<str:direction>/", views.move_block_view, name="move_block"),
    path("teacher/blocks/<int:block_id>/regenerate-content/", views.regenerate_block_content, name="regenerate_block_content"),
    path("teacher/blocks/<int:block_id>/update/<str:field_name>/", views.update_block_field, name="update_block_field"),
    path("teacher/blocks/<int:block_id>/config/<str:field_name>/", views.update_block_config_field, name="update_block_config_field"),
    path("teacher/blocks/<int:block_id>/projects/create/", views.block_project_create, name="block_project_create"),
    path("teacher/blocks/<int:block_id>/projects/export/", views.block_project_results_export, name="block_project_results_export"),
    path("teacher/blocks/<int:block_id>/upload/", views.asset_upload, name="asset_upload"),
    path("teacher/block-projects/<int:project_id>/update/", views.block_project_update, name="block_project_update"),
    path("teacher/block-projects/<int:project_id>/publish/", views.block_project_publish, name="block_project_publish"),
    path("teacher/block-projects/<int:project_id>/archive/", views.block_project_archive_view, name="block_project_archive"),
    path(
        "teacher/block-projects/<int:project_id>/preview-artifacts/<str:artifact_key>/download/",
        views.block_project_preview_artifact_download,
        name="block_project_preview_artifact_download",
    ),
    path("teacher/assets/<int:asset_id>/delete/", views.delete_asset, name="delete_asset"),
    path("teacher/objectives/<int:objective_id>/move/<str:direction>/", views.move_learning_objective_view, name="move_learning_objective"),
    path("teacher/assets/<int:asset_id>/toggle/", views.toggle_asset_generation, name="toggle_asset_generation"),
    path("teacher/objectives/<int:objective_id>/update/", views.update_learning_objective, name="update_learning_objective"),
    path("teacher/objectives/<int:objective_id>/delete/", views.delete_learning_objective_view, name="delete_learning_objective"),
    path(
        "teacher/objective-corrections/<int:correction_id>/delete/",
        views.delete_learning_objective_correction,
        name="delete_learning_objective_correction",
    ),
    path("teacher/validation-events/<int:event_id>/pack.pdf", views.validation_pack_pdf, name="validation_pack_pdf"),
    path("student/", views.student_dashboard, name="student_dashboard"),
    path("student/invite/<uuid:token>/", views.student_activate, name="student_activate"),
    path("courses/<slug:course_slug>/self-enrol/", views.self_enrol, name="self_enrol"),
    path("courses/magic/<uuid:token>/", views.magic_enrol, name="magic_enrol"),
    path("student/validation-events/<int:event_id>/book/", views.validation_book, name="validation_book"),
    path("student/validation-events/<int:event_id>/start/", views.validation_start, name="validation_start"),
    path("student/bookings/<int:booking_id>/cancel/", views.validation_cancel, name="validation_cancel"),
    path("student/courses/<int:course_id>/validate/", views.student_validate, name="student_validate"),
    path("student/validation-attempts/<int:attempt_id>/", views.validation_attempt, name="validation_attempt"),
    path(
        "student/validation-attempts/<int:attempt_id>/<str:action>/",
        views.validation_attempt_action,
        name="validation_attempt_action",
    ),
    path("student/courses/<int:course_id>/validation-practice/", views.validation_practice_session, name="validation_practice_session"),
    path(
        "student/courses/<int:course_id>/validation-practice/<int:attempt_id>/<str:action>/",
        views.validation_practice_action,
        name="validation_practice_action",
    ),
    path(
        "student/courses/<int:course_id>/practice/blocks/<int:block_id>/<str:action>/",
        views.student_practice_action,
        name="student_practice_action",
    ),
    path("projects/artifacts/<int:artifact_id>/download/", views.project_artifact_download, name="project_artifact_download"),
    path("student/courses/<int:course_id>/practice/", views.practice_quiz, name="practice_quiz"),
    path("courses/demo/<uuid:token>/", views.demo_practice, name="demo_practice"),
    path(
        "courses/demo/<uuid:token>/blocks/<int:block_id>/<str:action>/",
        views.demo_practice_action,
        name="demo_practice_action",
    ),
    path("courses/demo/<uuid:token>/validation-practice/", views.demo_validation_practice, name="demo_validation_practice"),
    path(
        "courses/demo/<uuid:token>/validation-practice/<str:action>/",
        views.demo_validation_practice_action,
        name="demo_validation_practice_action",
    ),
]
