# Generated by Django 5.2.7 on 2026-06-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0002_learningobjective_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningobjective',
            options={'ordering': ['block__order', 'position', 'pk']},
        ),
    ]
