# Generated by Django 5.2.7 on 2026-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0003_alter_learningobjective_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseblock',
            name='regeneration_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseblock',
            name='regeneration_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseblock',
            name='regeneration_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
