# Generated by Django 5.2.7 on 2026-06-18 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0011_practicemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='standalone/imports/%Y/%m/%d')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('creating', 'Creating blocks'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='standalone.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseImportChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('start_page', models.PositiveIntegerField(default=1)),
                ('end_page', models.PositiveIntegerField(default=1)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('selected', models.BooleanField(default=True)),
                ('course_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='standalone.courseimport')),
                ('created_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_chapters', to='standalone.courseblock')),
            ],
            options={
                'ordering': ['order', 'start_page', 'pk'],
                'unique_together': {('course_import', 'order')},
            },
        ),
    ]
