# Generated by Django 5.2.7 on 2026-06-19 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0012_courseimport_courseimportchapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfig',
            name='coding_question_ratio_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='code_snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='coding_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='coding_question_kind',
            field=models.CharField(blank=True, choices=[('comprehension', 'Code comprehension'), ('debug', 'Debugging')], max_length=30),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='is_coding_question',
            field=models.BooleanField(default=False),
        ),
    ]
