# Generated by Django 5.2.7 on 2026-06-19 07:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0013_courseconfig_coding_question_ratio_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationevent',
            name='audit_prompt_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='validationevent',
            name='feedback_release_mode',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('manual', 'Manual release')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='validationevent',
            name='mode',
            field=models.CharField(choices=[('self', 'Self-validation'), ('digital_invigilation', 'Digital invigilation'), ('paper_invigilation', 'Paper invigilation')], default='self', max_length=30),
        ),
        migrations.AddField(
            model_name='validationevent',
            name='room_code_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='validationevent',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='ValidationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('self', 'Self-validation'), ('digital_invigilation', 'Digital invigilation'), ('paper_invigilation', 'Paper invigilation')], max_length=30)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback_release_mode', models.CharField(choices=[('immediate', 'Immediate'), ('manual', 'Manual release')], default='immediate', max_length=20)),
                ('review_released_at', models.DateTimeField(blank=True, null=True)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt', to='standalone.validationbooking')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempts', to='standalone.enrollment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='standalone.validationevent')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('enrollment', 'event')},
            },
        ),
        migrations.AddField(
            model_name='validationsubmission',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='standalone.validationattempt'),
        ),
        migrations.CreateModel(
            name='ValidationAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('mcq', 'Single-answer'), ('maq', 'Multiple-answer'), ('waq', 'Written-answer')], max_length=20)),
                ('selected_answers', models.JSONField(blank=True, default=list)),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='standalone.validationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempt_questions', to='standalone.questionbankitem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('attempt', 'order'), ('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ValidationAttemptMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_blocks', models.JSONField(blank=True, default=list)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='standalone.validationattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_attempt_messages', to='standalone.questionbankitem')),
                ('attempt_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='standalone.validationattemptquestion')),
            ],
            options={
                'ordering': ['attempt', 'sequence', 'created_at'],
                'unique_together': {('attempt', 'message_id'), ('attempt', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ValidationAuditPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_index', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField()),
                ('expected_code', models.CharField(max_length=64)),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_code', models.CharField(blank=True, max_length=64)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_prompts', to='standalone.validationattempt')),
            ],
            options={
                'ordering': ['attempt', 'prompt_index', 'due_at'],
                'unique_together': {('attempt', 'prompt_index')},
            },
        ),
    ]
