# Generated by Django 5.2.7 on 2026-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0014_validationevent_audit_prompt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationattempt',
            name='invalidated_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='validationattempt',
            name='navigation_warning_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationevent',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='validation_events', to='standalone.courseblock'),
        ),
        migrations.AlterField(
            model_name='validationattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('voided', 'Voided')], default='in_progress', max_length=20),
        ),
    ]
