# Generated by Django 5.2.7 on 2026-06-21 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0017_courseconfig_numeric_ratio_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfig',
            name='assistant_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='assistant_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LearningObjectiveCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.TextField()),
                ('question_stem_snapshot', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_objective_corrections_created', to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='standalone.learningobjective')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_objective_corrections', to='standalone.questionbankitem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
