# Generated by Django 5.2.7 on 2026-06-25 07:11

import django.core.validators
import django.db.models.deletion
import standalone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0022_courseconfig_pre_engagement_and_half_life'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('engine_type', models.CharField(blank=True, choices=[('tabular_analysis', 'Tabular analysis'), ('seeded_script_output', 'Seeded script output')], max_length=30)),
                ('teacher_prompt', models.TextField()),
                ('example_text', models.TextField(blank=True)),
                ('student_instructions', models.TextField(blank=True)),
                ('answer_label', models.CharField(default='Answer', max_length=120)),
                ('answer_unit', models.CharField(blank=True, max_length=40)),
                ('decimal_places', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('spec_json', models.JSONField(blank=True, default=dict)),
                ('hint_plan_json', models.JSONField(blank=True, default=dict)),
                ('generation_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='idle', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='standalone.courseblock')),
            ],
            options={
                'ordering': ['block__order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.CharField(max_length=32)),
                ('expected_answer_display', models.CharField(max_length=120)),
                ('normalized_expected_answer', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('latest_submitted_answer', models.TextField(blank=True)),
                ('latest_normalized_answer', models.CharField(blank=True, max_length=120)),
                ('engine_payload_json', models.JSONField(blank=True, default=dict)),
                ('block_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='standalone.blockproject')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='standalone.enrollment')),
            ],
            options={
                'ordering': ['enrollment', 'block_project', 'created_at'],
                'unique_together': {('enrollment', 'block_project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('dataset', 'Dataset'), ('starter_script', 'Starter script'), ('supporting_file', 'Supporting file')], max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=standalone.models.project_artifact_upload_to)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='standalone.projectassignment')),
            ],
            options={
                'ordering': ['assignment', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_answer', models.TextField(blank=True)),
                ('normalized_answer', models.CharField(blank=True, max_length=120)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback_code', models.CharField(blank=True, max_length=40)),
                ('feedback_text', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='standalone.projectassignment')),
            ],
            options={
                'ordering': ['assignment', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='standalone.projectassignment')),
            ],
            options={
                'ordering': ['assignment', 'sequence', 'created_at'],
                'unique_together': {('assignment', 'message_id'), ('assignment', 'sequence')},
            },
        ),
    ]
