# Generated by Django 5.2.7 on 2026-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0026_coursedemoaccess_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_auto_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_daily_pair_cap',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='question_bank_builder_total_pair_cap',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
