# Generated by Django 5.2.7 on 2026-06-27 18:20

from django.db import migrations, models


def migrate_course_import_statuses(apps, schema_editor):
    CourseImport = apps.get_model("standalone", "CourseImport")
    CourseImport.objects.filter(status="uploaded").update(status="queued_analysis")


class Migration(migrations.Migration):

    dependencies = [
        ("standalone", "0027_courseconfig_question_bank_builder_auto_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseimport",
            name="current_step",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="courseimport",
            name="failed_chapter_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseimport",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseimport",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseimport",
            name="lease_owner",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="courseimport",
            name="processed_chapter_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseimportchapter",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courseimportchapter",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="courseimportchapter",
            name="preview_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="courseimportchapter",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="courseimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued_analysis", "Queued for analysis"),
                    ("analyzing", "Analyzing"),
                    ("ready", "Ready"),
                    ("queued_creation", "Queued for block creation"),
                    ("creating", "Creating blocks"),
                    ("paused", "Paused"),
                    ("attention", "Needs attention"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued_analysis",
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_course_import_statuses, migrations.RunPython.noop),
        migrations.AddField(
            model_name="courseimport",
            name="current_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="active_imports",
                to="standalone.courseimportchapter",
            ),
        ),
    ]
