# Generated by Django 5.2.7 on 2026-06-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standalone", "0028_harden_course_import_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningobjective",
            name="symbol_heuristics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
